 <?php

    $favouritelist = $this->getFavouritelist();
	
	
?>  
	
	<div class="my-account">
	 <div class="my-favouritelist">
        <div class="page-title title-buttons">
                        <h1>My Favouritelist</h1>
        </div>
		    <?php 
			
			if($favouritelist->getSize())
			{
			?>
			<form method="post" action="<?php echo Mage::getBaseUrl(); ?>favouritelist/index/update" id="favouritelist-view-form">
               <div class="fieldset">
           <table id="favouritelist-table" class="clean-table linearize-table">
			<thead>
				<tr class="first last">
									<th class="customer-favouritelist-item-image"></th>
									<th class="customer-favouritelist-item-info"></th>
									<th class="customer-favouritelist-item-quantity">Qty</th>
									<th class="customer-favouritelist-item-price">Price</th>
									<th class="customer-favouritelist-item-cart"></th>
									<th class="customer-favouritelist-item-remove"></th>
							</tr>
			</thead>
            <tbody>
			
			  <?php
			  
			  foreach($favouritelist as $fdata)
			  {
			     
				
			 
				 $_product = Mage::getModel('catalog/product')->load($fdata->getProductid()); 
				
	
			  ?>		
                 <tr id="item_<?php echo $fdata->getId(); ?>" class="first odd">
                     <td class="favouritelist-cell0 customer-favouritelist-item-image">
						 <a title="Simple Product01" href="<?php echo  $_product->getProductUrl(); ?>" class="product-image">
						 
						  <img width="113" height="113" alt="Simple Product01" src="<?php echo Mage::helper('catalog/image')->init($_product , 'thumbnail');?>">
						</a>
                     </td>
					   <td class="favouritelist-cell1 customer-favouritelist-item-info">
							   <h3 class="product-name">
								<a title="Simple Product01" href="<?php echo $_product->getProductUrl();?>">
								<?php echo $_product->getName();?></a>
								
							   </h3>

							<div class="favouritelist-sku">
								<span><?php echo $_product->getSku();?></span>
							</div>


					   </td>
					   
						 <td data-rwd-label="Qty" class="favouritelist-cell2 customer-favouritelist-item-quantity">
						  <div class="cart-cell">
						    <div class="add-to-cart-alt">
							<?php if($fdata->getProducttype()!='grouped'){ ?>
								<input type="text" value="<?php echo $fdata->getProductqty() ?>" name="qty[<?php echo  $fdata->getId(); ?>]" class="input-text qty validate-not-negative-number" pattern="\d*">
							<?php
							}
							?>
							</div>
					      </div>
					    </td>
                       <td data-rwd-label="Price" class="favouritelist-cell3 customer-favouritelist-item-price">
					    <div class="cart-cell">
    						  <div class="price-box">
									<span id="product-price-1" class="regular-price">
									  <span class="price">
									  <?php 
									  
									  if($fdata->getProducttype()=='grouped'){
									  $grpprice=0;
									      $super_group=unserialize($fdata->getSuperGroup());
										  
										  foreach($super_group as $pid=>$pqty)
										  {
										    
											
											if($pqty>0)
											{
											  $prduct = Mage::getModel('catalog/product')->load($pid); 
											  
											  $grpprice=$grpprice+($prduct->getPrice()*$pqty);
											}
											
										  }
									    echo Mage::helper('core')->currency($grpprice, true, false);
									   }else
									   {
                                        echo Mage::helper('core')->currency($_product->getPrice(), true, false);
                                      }
  									  ?>
									  
									  </span>    
								   </span>
												
								</div>

						</div>
                     </td>
                     <td class="favouritelist-cell4 customer-favouritelist-item-cart">
					 <div class="cart-cell">
					   <button class="button btn-cart" onclick="setLocation('<?php echo Mage::getBaseUrl(); ?>favouritelist/index/additem/item/<?php echo $fdata->getId();?>');" title="Add to Cart" type="button">
						<span><span>Add to Cart</span></span>
					  </button>
                     </div>
					   <p>
						 <a href="<?php echo Mage::getBaseUrl() ?>favouritelist/index/configure/flid/<?php echo $fdata->getId();?>/" class="link-edit button button-secondary">Edit</a>
					   </p>
    

                 </td>
					<td class="favouritelist-cell5 customer-favouritelist-item-remove last">
					<a class="btn-remove btn-remove2" title="Remove Item" onclick="return confirmRemoveFavouritelist();" href="<?php echo Mage::getBaseUrl(); ?>favouritelist/index/removeitem/item/<?php echo $fdata->getId();?>">Remove item</a>
				 </td>
            </tr>
        	<?php


			}

			?>     
	   </tbody>
     </table>
           <script type="text/javascript">decorateTable('favouritelist-table')</script>
              <div class="buttons-set buttons-set2">
           
              <button class="button btn-add" onclick="setLocation('<?php echo Mage::getBaseUrl(); ?>favouritelist/index/addallitem'); return false;" title="Add All to Cart" type="button"><span><span>Add All to Cart</span></span></button>

                 <button class="button btn-update button-secondary" title="Update favouritelist" name="do" type="submit"><span><span>Update Favouritelist</span></span></button>
             </div>
            </div>
			</form>
       
            <?php
			
			}else
			 {
			?>
             <div class="fieldset">
                           <p class="favouritelist-empty">You have no items in your favouritelist.</p>
                              
            </div>
           <?php
		   }
		   ?>
            </div>
        
		
		</div>
		<script>
		
		function confirmRemoveFavouritelist() {
            return confirm('Are you sure you want to remove this product from your favouritelist?');
        }
		
		</script>